// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuS7PB-67yL1H52-RAzSppayIWdx2vVJw',
    appId: '1:488691680555:web:b524029104743c0326b16e',
    messagingSenderId: '488691680555',
    projectId: 'chat-app-7b114',
    authDomain: 'chat-app-7b114.firebaseapp.com',
    storageBucket: 'chat-app-7b114.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzKqG7aa8YDoih2kIF9rxTdiAUO7OLiFQ',
    appId: '1:488691680555:android:5cef0d58cd05655c26b16e',
    messagingSenderId: '488691680555',
    projectId: 'chat-app-7b114',
    storageBucket: 'chat-app-7b114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMeMdNtp263Nfx_WeUASHGs83cCr7XBr8',
    appId: '1:488691680555:ios:c7ef06105dd0ac2726b16e',
    messagingSenderId: '488691680555',
    projectId: 'chat-app-7b114',
    storageBucket: 'chat-app-7b114.appspot.com',
    iosClientId: '488691680555-pba1ppfoclvdidiqga2tck3d77pkr8rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
